### ISSUE TITLE
Update TB Coordinators List

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/GA-TB-Reference-Guide-Web#24]
# Content Update

## Context from clients
"I have the pleasure of introducing Lucas O’Reilly, the new TB Coordinator for DeKalb County!  Please welcome him! As of last week Lucas became the TB-Refugee Program Coordinator over here at DeKalb Public Health. He’s originally from Marietta, GA, but received his undergraduate degree from Centre College in Kentucky, and his MPH at Georgia State. He’s been with District 3-5 since 2020 where he originally started as a COVID-19 Case Investigator during the peak of the pandemic. From there, Lucas began working as an Epidemiologist, where he was placed here in DeKalb at the onset of the Mpox outbreak. After a few years in Epi, and with his fellowship coming to an end, there was an opportunity and need for him to switch over to the TB and Refugee Programs where he is very excited to continue to grow in his public health career with this new challenge! Lucas looks very much forward to learning as much as he can and to meeting everyone over his time in this new position."

File available here
https://www.notion.so/apphatchery/September-2024-8fbe39e41e8842f883db5b38f7d78595

**Comment by yago1994** [comment]
@MaxwellKJrm @Naomi-Nyama I'm going to put this on your radar, I've reduced the scope of M2 release by removing the Bookmarks and we are going to focus on just search and on updating the content from the Web repository, making sure that the TB coordinators list is updated (they've had some recent staff changes)

I'd like to aim for next Friday as the release date, let me know if you guys think we are too far away in development from that

**Comment by Naomi-Nyama** [comment]
> @MaxwellKJr @Naomi-Nyama I'm going to put this on your radar, I've reduced the scope of M2 release by removing the Bookmarks and we are going to focus on just search and on updating the content from the Web repository, making sure that the TB coordinators list is updated (they've had some recent staff changes)
> 
> I'd like to aim for next Friday as the release date, let me know if you guys think we are too far away in development from that

@yago1994 From the android section I think we can try to make next Friday work if its just the search component, we can go over everything in today's meeting
